# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: tech-notes-press

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.16.0]
        #node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run docs:build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tech-note-press-v${{ github.run_number }}-${{ github.run_attempt }}
          path: |
            ./artifacts
#      - run: ls
#      - run: npm run build --if-present
#      - run: npm test
#      - name: Output Run ID
#        run: echo "Run ID:" ${{ github.run_id }} "Run:" ${{ github.run_number }}"::"${{ github.run_attempt }}
#      - name: Output Run Number
#        run: echo ${{ github.run_number }}
#      - name: Output Run Attempt
#        run: echo ${{ github.run_attempt }}

  deploy:
    runs-on: 'ubuntu-latest'
#    environment: 'production'
    needs: [build]
    steps:
#      - name: Output Run ID
#        run: echo "deploy Run ID:" ${{ github.run_id }} "Run:" ${{ github.run_number }}"::"${{ github.run_attempt }}
      # Download published artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tech-note-press-v${{ github.run_number }}-${{ github.run_attempt }}
          path: './artifacts'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./artifacts s3://zxtech-notes-press --delete
